#!/bin/bash

# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  cloud_config_needs vm_type    $(lookup params.vm_type    small)
  cloud_config_needs network    $(lookup params.network    default)
  cloud_config_needs disk_type  $(lookup params.disk_pool  small)
  check_cloud_config && describe "  cloud-config [#G{OK}]"
fi
