#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]; then

      echo; echo;
  describe "#M{$GENESIS_ENVIRONMENT} NFS Broker deployed!"
      echo
      echo "For details about the deployment, run"
      echo
  describe "  #G{genesis info $GENESIS_ENVIRONMENT}"
      echo
      echo "To register the NFS Broker with Cloud Foundry, run"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT -- register}"
      echo

fi
